### ISSUE TITLE
Redirigir fichas de indultos al indulto en el BOE

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/elindultometro#21]
Al rehacer el buscador de indultos ya no enlazamos a las páginas de detalle de un indulto (por ejemplo, https://elindultometro.es/indulto.html?id=BOE-A-2009-2192) sino que enlazamos directamente al indulto en el BOE (por ejemplo, http://www.boe.es/diario_boe/txt.php?id=BOE-A-2009-2192).
Por tanto habría que añadir una redirección para que todas las urls `https://elindultometro.es/indulto.html?id=ID` lleven a  `http://www.boe.es/diario_boe/txt.php?id=ID`.

**Comment by esebastian** [comment]
Dado que la _querystring_ es la misma, ha bastado con reescribir el _path_ de la URL:
```
rewrite ^/indulto.html$ https://www.boe.es/diario_boe/txt.php permanent;
```
